[package]
name = "rda-game/cozy-coffee"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@^2"
Fusion = "elttob/fusion@0.1.1-beta"
Knit = "sleitnick/knit@^1"
Signal = "sleitnick/signal@^1"
T = "osyrisrblx/t@^3"
TableUtil = "sleitnick/table-util@^1"
Trove = "sleitnick/trove@^0"

[server-dependencies]
ProfileService = "rudy-dev/profileservice@^1"
