name: lint

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-lint]')"
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
      - name: Setup Aftman v0.3.0
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Selene
        run: selene src/
      - name: Lint
        run: stylua --check src/
